### ISSUE TITLE
How to build MP3 file using sequence of small MP3 file & MIDI data 

### ISSUE THREAD

**Issue by shivrajsa** [audiocogs/mp3.js#24] opened 2017-02-17 05:52 UTC
I am wondering if this is right place to ask this question, but I think at least my question will be directed to experts of this topic

I have developed an application using [MIDI.js](https://github.com/mudcube/MIDI.js) where I am playing sequence of notes [ small base64 MP3 files ]using MIDI protocol. So I have two types of data 
1. Small base64 MP3 files extracted from .SF2 file for each note
2. MIDI protocol for each note of sequence i.e. Velocity, Duration, etc.

I want to build single MP3 file using this data.  Could you please guide to progress on this requirement.

**Comment by fasterthanlime** [comment] 2017-02-17 09:22
You'll need an encoder for that! mp3.js is just a decoder.

**Comment by shivrajsa** [comment] 2017-02-17 11:02
@fasterthanlime my each MP3 file is encoded in base64 format. And I want to create single MP3 file by joining sequence of such MP3s with MIDI protocol.

I posted this question here, because I think authors of audiocogs libraries are expert in this area and may guide me to correct direction / steps to achieve that.

**Comment by fasterthanlime** [comment] 2017-02-17 11:09
Yep! And the first step is: you need an mp3 encoder.

You'll basically need to:

  * Decode all MP3 files
  * "Render" the MIDI data into a single stream, using the notes you decoded
  * Encode that stream as an MP3 file

There's really no way around it, MP3 files can't be concatenated in compressed form (even less overlaid on top of one another!)

**Comment by UCIS** [comment] 2017-02-18 12:29
Actually you can just concatenate MP3 files in compressed form. It's not pretty, but if all the MP3 files are complete (no partial bit reservoir at the beginning) and are similar (number of channels, maybe bitrate mode and bitrate) or if you have a decent decoder, it should work. There may be gaps of silence or glitches in between files, and timestamp calculations by the player may be incorrect. This works because the MP3 format was designed to be self synchronizing and tolerant of errors in the stream.

**Comment by fasterthanlime** [comment] 2017-02-18 16:02
> Actually you can just concatenate MP3 files

Let me revise my comment with "really shouldn't" then.

More importantly, concatenation isn't enough for what the OP wanted to do.

By the way, we finished up that discussion by e-mail, so I'm going to close this issue since it's not directly an mp3.js issue.

**Closed as completed by fasterthanlime** 2017-02-18 16:02 UTC
